/**
 * Normaliseert tekst voor pdf-lib standaardfonts (WinAnsi).
 * Vervangt Unicode met ASCII-equivalenten zodat o.a. Hongaarse namen werken.
 */
export function normalizeTextForPDF(text: string): string {
  if (!text) return text

  const normalized = text
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[^\x00-\x7F]/g, (char) => {
      const replacements: Record<string, string> = {
        ą: "a",
        Ą: "A",
        ć: "c",
        Ć: "C",
        ę: "e",
        Ę: "E",
        ł: "l",
        Ł: "L",
        ń: "n",
        Ń: "N",
        ó: "o",
        Ó: "O",
        ś: "s",
        Ś: "S",
        ź: "z",
        Ź: "Z",
        ż: "z",
        Ż: "Z",
        č: "c",
        Č: "C",
        š: "s",
        Š: "S",
        ž: "z",
        Ž: "Z",
        đ: "d",
        Đ: "D",
        ő: "o",
        Ő: "O",
        ű: "u",
        Ű: "U",
        ñ: "n",
        Ñ: "N",
        ü: "u",
        Ü: "U",
        ö: "o",
        Ö: "O",
        ä: "a",
        Ä: "A",
        ÿ: "y",
        Ÿ: "Y",
        à: "a",
        á: "a",
        â: "a",
        ã: "a",
        å: "a",
        À: "A",
        Á: "A",
        Â: "A",
        Ã: "A",
        Å: "A",
        è: "e",
        é: "e",
        ê: "e",
        ë: "e",
        È: "E",
        É: "E",
        Ê: "E",
        Ë: "E",
        ì: "i",
        í: "i",
        î: "i",
        ï: "i",
        Ì: "I",
        Í: "I",
        Î: "I",
        Ï: "I",
        ò: "o",
        ô: "o",
        õ: "o",
        Ò: "O",
        Ô: "O",
        Õ: "O",
        ù: "u",
        ú: "u",
        û: "u",
        Ù: "U",
        Ú: "U",
        Û: "U",
        ý: "y",
        Ý: "Y",
        æ: "ae",
        Æ: "AE",
        œ: "oe",
        Œ: "OE",
        ß: "ss",
        "…": "...",
        "·": "-",
      }
      return replacements[char] || ""
    })

  return normalized.replace(/[^\x00-\x7F]/g, "")
}
